"""sp img file name

Revision ID: 6d07539ac00f
Revises: 2840e6973550
Create Date: 2025-09-01 14:58:49.360096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d07539ac00f'
down_revision: Union[str, Sequence[str], None] = '2840e6973550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_product', sa.Column('img_file_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'sub_product', ['img_file_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sub_product', type_='unique')
    op.drop_column('sub_product', 'img_file_name')
    # ### end Alembic commands ###
