"""category route

Revision ID: e2ca9d671c98
Revises: a52a81f5d85a
Create Date: 2025-08-29 21:05:08.700201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ca9d671c98'
down_revision: Union[str, Sequence[str], None] = 'a52a81f5d85a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('route', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'route')
    # ### end Alembic commands ###
