"""product imgurl

Revision ID: 2840e6973550
Revises: be4c56e5d1df
Create Date: 2025-08-31 18:01:39.051855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2840e6973550'
down_revision: Union[str, Sequence[str], None] = 'be4c56e5d1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('category_nav_order_uc'), 'category', type_='unique')
    op.create_unique_constraint('category_nav_route_uc', 'category', ['nav_id', 'route'])
    op.add_column('product', sa.Column('img_url', sa.String(), nullable=False))
    op.drop_constraint(op.f('series_id_product_order_uc'), 'product', type_='unique')
    op.drop_constraint(op.f('category_sub_category_order_uc'), 'sub_category', type_='unique')
    op.drop_constraint(op.f('sub_product_id_order_uc'), 'sub_product', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('sub_product_id_order_uc'), 'sub_product', ['product_id', 'order'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('category_sub_category_order_uc'), 'sub_category', ['category_id', 'order'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('series_id_product_order_uc'), 'product', ['series_id', 'order'], postgresql_nulls_not_distinct=False)
    op.drop_column('product', 'img_url')
    op.drop_constraint('category_nav_route_uc', 'category', type_='unique')
    op.create_unique_constraint(op.f('category_nav_order_uc'), 'category', ['nav_id', 'order'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
