"""order

Revision ID: be4c56e5d1df
Revises: e2ca9d671c98
Create Date: 2025-08-29 21:43:14.261374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be4c56e5d1df'
down_revision: Union[str, Sequence[str], None] = 'e2ca9d671c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['order'])
    op.create_unique_constraint(None, 'nav', ['order'])
    op.create_unique_constraint(None, 'product', ['order'])
    op.create_unique_constraint(None, 'sub_category', ['order'])
    op.create_unique_constraint(None, 'sub_product', ['order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sub_product', type_='unique')
    op.drop_constraint(None, 'sub_category', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'nav', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
