"""size sp optional

Revision ID: dd92a850f360
Revises: 6d07539ac00f
Create Date: 2025-09-01 23:58:55.190512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd92a850f360'
down_revision: Union[str, Sequence[str], None] = '6d07539ac00f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('size_sub_product', 'is_show',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('size_sub_product', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('size_sub_product', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('size_sub_product', 'is_show',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
