"""nav + img_file_name

Revision ID: e8464f18a2d4
Revises: dd92a850f360
Create Date: 2025-09-03 21:18:46.496441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8464f18a2d4'
down_revision: Union[str, Sequence[str], None] = 'dd92a850f360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nav', sa.Column('img_file_name', sa.String(), nullable=False,server_default=""))
    
    # 3. 設為 NOT NULL
    op.alter_column('nav', 'img_file_name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nav', 'img_file_name')
    # ### end Alembic commands ###
