name: Deploy Backend

on:
  push:
    branches:
      - main  # 或你要自動部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: SSH Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          script: |
            export PATH="/home/ubuntu/.local/bin:$PATH"
            export APP_DIR=/home/ubuntu/fastapi
            export BACKEND_DIR=/home/ubuntu/fastapi/backend
            export ENVIRONMENT=prod

            REPO_URL=https://${{ secrets.GITHUB_TOKEN }}@github.com/mikemikemikemikemmmm/lativ-nextjs-fastapi.git
            # 把vps的PATH注入到shell環境

            # 如果目錄不存在，先建立並 clone
            if [ ! -d "$APP_DIR" ]; then
              mkdir -p $APP_DIR
            fi

            if [ ! -d "$APP_DIR/.git" ]; then
              git clone $REPO_URL $APP_DIR
            else
              cd $APP_DIR
              git fetch --all
              git reset --hard origin/main
            fi
            # 進入專案資料夾
            cd $BACKEND_DIR
            
            echo ${{ secrets.ENV_FILE_CONTENT }}  > ./.env.$ENVIRONMENT
            echo "生成.env"

            echo "開始跑run.sh"
            bash ./scripts/$ENVIRONMENT/run.sh