name: Deploy Frontend Guest

on:
  push:
    branches: ['main']

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: ./frontend-guest-2/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend-guest-2
      - name: Inject environment variables
        run: |
            export ENVIRONMENT=prod
            cat <<EOF > ./.env.$ENVIRONMENT
            ${{ secrets.FRONTEND_GUEST_ENV_FILE_CONTENT }}
            EOF
        working-directory: ./frontend-guest-2
      - name: Build
        run: npm run build
        working-directory: ./frontend-guest-2
      - name: Deploy to gh-pages branch
        run: |
          npm install -g gh-pages
          gh-pages -d ./frontend-guest-2/dist -b gh-pages